import type { MetadataRoute } from "next";
import { SITE_NAME, BRAND_COLORS } from "@/lib/constants";

// Served at /manifest.webmanifest; Next auto-injects <link rel="manifest">.
// Icons are the committed PNGs generated by scripts/generate-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME} — University of Auckland Research`,
    short_name: SITE_NAME,
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: BRAND_COLORS.uoaWaitemata,
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icon-512-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
